---
log_level: trace
rest:
  hostname: ogbrest
  port: 8090
  allowed_origins:
    - http://localhost:3000
services:
  - label: user
    hostname: ogbuser
    port: 12121
    token: "random-token-for-user"
  - label: test
    hostname: ogbtest
    port: 9001
    token: "random-token-for-test"
user_client:
  hostname: ogbuser
  port: 12122
