// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: rest.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthenticateServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticateServiceRequest) Reset() {
	*x = AuthenticateServiceRequest{}
	mi := &file_rest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateServiceRequest) ProtoMessage() {}

func (x *AuthenticateServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateServiceRequest.ProtoReflect.Descriptor instead.
func (*AuthenticateServiceRequest) Descriptor() ([]byte, []int) {
	return file_rest_proto_rawDescGZIP(), []int{0}
}

func (x *AuthenticateServiceRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type AuthenticateServiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticateServiceResponse) Reset() {
	*x = AuthenticateServiceResponse{}
	mi := &file_rest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateServiceResponse) ProtoMessage() {}

func (x *AuthenticateServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateServiceResponse.ProtoReflect.Descriptor instead.
func (*AuthenticateServiceResponse) Descriptor() ([]byte, []int) {
	return file_rest_proto_rawDescGZIP(), []int{1}
}

func (x *AuthenticateServiceResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *AuthenticateServiceResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type RestDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       int32                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestDataRequest) Reset() {
	*x = RestDataRequest{}
	mi := &file_rest_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestDataRequest) ProtoMessage() {}

func (x *RestDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rest_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestDataRequest.ProtoReflect.Descriptor instead.
func (*RestDataRequest) Descriptor() ([]byte, []int) {
	return file_rest_proto_rawDescGZIP(), []int{2}
}

func (x *RestDataRequest) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type RestDataDefinition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Root          string                 `protobuf:"bytes,3,opt,name=root,proto3" json:"root,omitempty"`
	EndpointsNum  int32                  `protobuf:"varint,4,opt,name=endpoints_num,json=endpointsNum,proto3" json:"endpoints_num,omitempty"`
	Endpoints     []*RestEndpoint        `protobuf:"bytes,5,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	Version       string                 `protobuf:"bytes,6,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestDataDefinition) Reset() {
	*x = RestDataDefinition{}
	mi := &file_rest_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestDataDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestDataDefinition) ProtoMessage() {}

func (x *RestDataDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_rest_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestDataDefinition.ProtoReflect.Descriptor instead.
func (*RestDataDefinition) Descriptor() ([]byte, []int) {
	return file_rest_proto_rawDescGZIP(), []int{3}
}

func (x *RestDataDefinition) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *RestDataDefinition) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *RestDataDefinition) GetRoot() string {
	if x != nil {
		return x.Root
	}
	return ""
}

func (x *RestDataDefinition) GetEndpointsNum() int32 {
	if x != nil {
		return x.EndpointsNum
	}
	return 0
}

func (x *RestDataDefinition) GetEndpoints() []*RestEndpoint {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

func (x *RestDataDefinition) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type RestEndpoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestEndpoint) Reset() {
	*x = RestEndpoint{}
	mi := &file_rest_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestEndpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestEndpoint) ProtoMessage() {}

func (x *RestEndpoint) ProtoReflect() protoreflect.Message {
	mi := &file_rest_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestEndpoint.ProtoReflect.Descriptor instead.
func (*RestEndpoint) Descriptor() ([]byte, []int) {
	return file_rest_proto_rawDescGZIP(), []int{4}
}

func (x *RestEndpoint) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *RestEndpoint) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

type RestApiRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uri           string                 `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Headers       []*RestHeader          `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty"`
	Body          string                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	Source        string                 `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestApiRequest) Reset() {
	*x = RestApiRequest{}
	mi := &file_rest_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestApiRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestApiRequest) ProtoMessage() {}

func (x *RestApiRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rest_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestApiRequest.ProtoReflect.Descriptor instead.
func (*RestApiRequest) Descriptor() ([]byte, []int) {
	return file_rest_proto_rawDescGZIP(), []int{5}
}

func (x *RestApiRequest) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *RestApiRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *RestApiRequest) GetHeaders() []*RestHeader {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *RestApiRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *RestApiRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type RestApiResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Headers       []*RestHeader          `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty"`
	Body          string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestApiResponse) Reset() {
	*x = RestApiResponse{}
	mi := &file_rest_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestApiResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestApiResponse) ProtoMessage() {}

func (x *RestApiResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rest_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestApiResponse.ProtoReflect.Descriptor instead.
func (*RestApiResponse) Descriptor() ([]byte, []int) {
	return file_rest_proto_rawDescGZIP(), []int{6}
}

func (x *RestApiResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *RestApiResponse) GetHeaders() []*RestHeader {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *RestApiResponse) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type RestHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestHeader) Reset() {
	*x = RestHeader{}
	mi := &file_rest_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestHeader) ProtoMessage() {}

func (x *RestHeader) ProtoReflect() protoreflect.Message {
	mi := &file_rest_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestHeader.ProtoReflect.Descriptor instead.
func (*RestHeader) Descriptor() ([]byte, []int) {
	return file_rest_proto_rawDescGZIP(), []int{7}
}

func (x *RestHeader) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *RestHeader) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_rest_proto protoreflect.FileDescriptor

var file_rest_proto_rawDesc = string([]byte{
	0x0a, 0x0a, 0x72, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x72, 0x65,
	0x73, 0x74, 0x22, 0x32, 0x0a, 0x1a, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61,
	0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x47, 0x0a, 0x1b, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e,
	0x74, 0x69, 0x63, 0x61, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22,
	0x2b, 0x0a, 0x0f, 0x52, 0x65, 0x73, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0xc3, 0x01, 0x0a,
	0x12, 0x52, 0x65, 0x73, 0x74, 0x44, 0x61, 0x74, 0x61, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x12, 0x0a,
	0x04, 0x72, 0x6f, 0x6f, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x6f, 0x6f,
	0x74, 0x12, 0x23, 0x0a, 0x0d, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x5f, 0x6e,
	0x75, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69,
	0x6e, 0x74, 0x73, 0x4e, 0x75, 0x6d, 0x12, 0x30, 0x0a, 0x09, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69,
	0x6e, 0x74, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x72, 0x65, 0x73, 0x74,
	0x2e, 0x52, 0x65, 0x73, 0x74, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x09, 0x65,
	0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x22, 0x3a, 0x0a, 0x0c, 0x52, 0x65, 0x73, 0x74, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69,
	0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x22, 0x92,
	0x01, 0x0a, 0x0e, 0x52, 0x65, 0x73, 0x74, 0x41, 0x70, 0x69, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x69, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x75, 0x72, 0x69, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x2a, 0x0a, 0x07, 0x68,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x72,
	0x65, 0x73, 0x74, 0x2e, 0x52, 0x65, 0x73, 0x74, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x07,
	0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x22, 0x65, 0x0a, 0x0f, 0x52, 0x65, 0x73, 0x74, 0x41, 0x70, 0x69, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x2a, 0x0a, 0x07, 0x68, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x72, 0x65,
	0x73, 0x74, 0x2e, 0x52, 0x65, 0x73, 0x74, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x07, 0x68,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x22, 0x34, 0x0a, 0x0a, 0x52, 0x65,
	0x73, 0x74, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x32, 0xee, 0x01, 0x0a, 0x10, 0x52, 0x65, 0x73, 0x74, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x57, 0x0a, 0x10, 0x41, 0x75, 0x74, 0x68, 0x49, 0x6e, 0x74,
	0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x20, 0x2e, 0x72, 0x65, 0x73, 0x74,
	0x2e, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x65, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x72, 0x65,
	0x73, 0x74, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x65, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x42,
	0x0a, 0x0f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x74, 0x44, 0x61, 0x74,
	0x61, 0x12, 0x15, 0x2e, 0x72, 0x65, 0x73, 0x74, 0x2e, 0x52, 0x65, 0x73, 0x74, 0x44, 0x61, 0x74,
	0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x72, 0x65, 0x73, 0x74, 0x2e,
	0x52, 0x65, 0x73, 0x74, 0x44, 0x61, 0x74, 0x61, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x3d, 0x0a, 0x0e, 0x4e, 0x65, 0x77, 0x52, 0x65, 0x73, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x2e, 0x72, 0x65, 0x73, 0x74, 0x2e, 0x52, 0x65, 0x73, 0x74,
	0x41, 0x70, 0x69, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x72, 0x65, 0x73,
	0x74, 0x2e, 0x52, 0x65, 0x73, 0x74, 0x41, 0x70, 0x69, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x42, 0x28, 0x5a, 0x26, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x73, 0x61, 0x76, 0x61, 0x67, 0x65, 0x6b, 0x69, 0x6e, 0x67, 0x2d, 0x69, 0x6f, 0x2f, 0x6f, 0x67,
	0x62, 0x72, 0x65, 0x73, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
})

var (
	file_rest_proto_rawDescOnce sync.Once
	file_rest_proto_rawDescData []byte
)

func file_rest_proto_rawDescGZIP() []byte {
	file_rest_proto_rawDescOnce.Do(func() {
		file_rest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rest_proto_rawDesc), len(file_rest_proto_rawDesc)))
	})
	return file_rest_proto_rawDescData
}

var file_rest_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_rest_proto_goTypes = []any{
	(*AuthenticateServiceRequest)(nil),  // 0: rest.AuthenticateServiceRequest
	(*AuthenticateServiceResponse)(nil), // 1: rest.AuthenticateServiceResponse
	(*RestDataRequest)(nil),             // 2: rest.RestDataRequest
	(*RestDataDefinition)(nil),          // 3: rest.RestDataDefinition
	(*RestEndpoint)(nil),                // 4: rest.RestEndpoint
	(*RestApiRequest)(nil),              // 5: rest.RestApiRequest
	(*RestApiResponse)(nil),             // 6: rest.RestApiResponse
	(*RestHeader)(nil),                  // 7: rest.RestHeader
}
var file_rest_proto_depIdxs = []int32{
	4, // 0: rest.RestDataDefinition.endpoints:type_name -> rest.RestEndpoint
	7, // 1: rest.RestApiRequest.headers:type_name -> rest.RestHeader
	7, // 2: rest.RestApiResponse.headers:type_name -> rest.RestHeader
	0, // 3: rest.RestInterService.AuthInterService:input_type -> rest.AuthenticateServiceRequest
	2, // 4: rest.RestInterService.RequestRestData:input_type -> rest.RestDataRequest
	5, // 5: rest.RestInterService.NewRestRequest:input_type -> rest.RestApiRequest
	1, // 6: rest.RestInterService.AuthInterService:output_type -> rest.AuthenticateServiceResponse
	3, // 7: rest.RestInterService.RequestRestData:output_type -> rest.RestDataDefinition
	6, // 8: rest.RestInterService.NewRestRequest:output_type -> rest.RestApiResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_rest_proto_init() }
func file_rest_proto_init() {
	if File_rest_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rest_proto_rawDesc), len(file_rest_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rest_proto_goTypes,
		DependencyIndexes: file_rest_proto_depIdxs,
		MessageInfos:      file_rest_proto_msgTypes,
	}.Build()
	File_rest_proto = out.File
	file_rest_proto_goTypes = nil
	file_rest_proto_depIdxs = nil
}
